version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433"
    networks:
      - jli-network

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
